server.port=5000
spring.datasource.url=jdbc:postgresql://ep-dawn-union-am0ctdj2-pooler.c-5.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SYNC3y8rdnIJ
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true